version: '1'
networks:
  privnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
services:
  gateway:
    build:
      context: ./manager
      args:
        - SERVICE_NAME=gateway
        - GIT_COMMIT=e7af253d480d6d2a7a71e0c3fd591032ed0a637c
    container_name: gateway
    entrypoint: /app/monster-reacher-server/gateway/gateway
    ports:
      - 20530:20530
    environment:
      - TZ=Asia/Bangkok
    networks:
      privnet:
        ipv4_address: 10.1.0.200
  services-discovery:
    build:
      context: ./manager
      args:
        - SERVICE_NAME=services-discovery
        - GIT_COMMIT=e7af253d480d6d2a7a71e0c3fd591032ed0a637c
    container_name: services-discovery
    entrypoint: /app/monster-reacher-server/services-discovery/services-discovery
    ports:
      - 20531:20531
    environment:
      - TZ=Asia/Bangkok
    networks:
      privnet:
        ipv4_address: 10.1.0.201

  microservice-wartech:
    build:
      context: ./microservices
      args:
        - SERVICE_NAME=wartech
        - GIT_COMMIT=e7af253d480d6d2a7a71e0c3fd591032ed0a637c
    container_name: microservice-wartech
    entrypoint: /app/monster-reacher-server/microservices/cmd/wartech/wartech
    ports:
      - 20560:20560
      - 20561:20561
    environment:
      - TZ=Asia/Bangkok
    networks:
      privnet:
        ipv4_address: 10.1.0.99

  microservice-authentication:
    build:
      context: ./microservices
      args:
        - SERVICE_NAME=authentication
        - GIT_COMMIT=e7af253d480d6d2a7a71e0c3fd591032ed0a637c
    container_name: microservice-authentication
    entrypoint: /app/monster-reacher-server/microservices/cmd/authentication/authentication
    ports:
      - 20541:20541
    environment:
      - TZ=Asia/Bangkok
    networks:
      privnet:
        ipv4_address: 10.1.0.100

  microservice-character:
    build:
      context: ./microservices
      args:
        - SERVICE_NAME=character
        - GIT_COMMIT=e7af253d480d6d2a7a71e0c3fd591032ed0a637c
    container_name: microservice-character
    entrypoint: /app/monster-reacher-server/microservices/cmd/character/character
    ports:
      - 20571:20571
    environment:
      - TZ=Asia/Bangkok
    networks:
      privnet:
        ipv4_address: 10.1.0.102

  microservice-profile:
    build:
      context: ./microservices
      args:
        - SERVICE_NAME=profile
        - GIT_COMMIT=e7af253d480d6d2a7a71e0c3fd591032ed0a637c
    container_name: microservice-profile
    entrypoint: /app/monster-reacher-server/microservices/cmd/profile/profile
    ports:
      - 20551:20551
    environment:
      - TZ=Asia/Bangkok
    networks:
      privnet:
        ipv4_address: 10.1.0.101

  envoyproxy:
    build:
      context: ./envoy
    container_name: envoyproxy
    ports:
      - 20520:20520
      - 9901:9901
    environment:
      - TZ=Asia/Bangkok
    networks:
      privnet:
        ipv4_address: 10.1.0.20