// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: wartech.proto

package wartech

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WartechClient is the client API for Wartech service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WartechClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Authentication(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error)
	CheckUserOrEmail(ctx context.Context, in *CheckUserOrEmailRequest, opts ...grpc.CallOption) (*CheckUserOrEmailResponse, error)
	ForgottenPassword(ctx context.Context, in *ForgottenPasswordRequest, opts ...grpc.CallOption) (*ForgottenPasswordResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	ConfirmEmail(ctx context.Context, in *ConfirmEmailRequest, opts ...grpc.CallOption) (*ConfirmEmailResponse, error)
}

type wartechClient struct {
	cc grpc.ClientConnInterface
}

func NewWartechClient(cc grpc.ClientConnInterface) WartechClient {
	return &wartechClient{cc}
}

func (c *wartechClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/wartech.Wartech/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wartechClient) Authentication(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error) {
	out := new(AuthenticationResponse)
	err := c.cc.Invoke(ctx, "/wartech.Wartech/Authentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wartechClient) CheckUserOrEmail(ctx context.Context, in *CheckUserOrEmailRequest, opts ...grpc.CallOption) (*CheckUserOrEmailResponse, error) {
	out := new(CheckUserOrEmailResponse)
	err := c.cc.Invoke(ctx, "/wartech.Wartech/CheckUserOrEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wartechClient) ForgottenPassword(ctx context.Context, in *ForgottenPasswordRequest, opts ...grpc.CallOption) (*ForgottenPasswordResponse, error) {
	out := new(ForgottenPasswordResponse)
	err := c.cc.Invoke(ctx, "/wartech.Wartech/ForgottenPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wartechClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/wartech.Wartech/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wartechClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/wartech.Wartech/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wartechClient) ConfirmEmail(ctx context.Context, in *ConfirmEmailRequest, opts ...grpc.CallOption) (*ConfirmEmailResponse, error) {
	out := new(ConfirmEmailResponse)
	err := c.cc.Invoke(ctx, "/wartech.Wartech/ConfirmEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WartechServer is the server API for Wartech service.
// All implementations must embed UnimplementedWartechServer
// for forward compatibility
type WartechServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Authentication(context.Context, *AuthenticationRequest) (*AuthenticationResponse, error)
	CheckUserOrEmail(context.Context, *CheckUserOrEmailRequest) (*CheckUserOrEmailResponse, error)
	ForgottenPassword(context.Context, *ForgottenPasswordRequest) (*ForgottenPasswordResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	ConfirmEmail(context.Context, *ConfirmEmailRequest) (*ConfirmEmailResponse, error)
	mustEmbedUnimplementedWartechServer()
}

// UnimplementedWartechServer must be embedded to have forward compatible implementations.
type UnimplementedWartechServer struct {
}

func (UnimplementedWartechServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWartechServer) Authentication(context.Context, *AuthenticationRequest) (*AuthenticationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authentication not implemented")
}
func (UnimplementedWartechServer) CheckUserOrEmail(context.Context, *CheckUserOrEmailRequest) (*CheckUserOrEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserOrEmail not implemented")
}
func (UnimplementedWartechServer) ForgottenPassword(context.Context, *ForgottenPasswordRequest) (*ForgottenPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgottenPassword not implemented")
}
func (UnimplementedWartechServer) ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedWartechServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedWartechServer) ConfirmEmail(context.Context, *ConfirmEmailRequest) (*ConfirmEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmEmail not implemented")
}
func (UnimplementedWartechServer) mustEmbedUnimplementedWartechServer() {}

// UnsafeWartechServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WartechServer will
// result in compilation errors.
type UnsafeWartechServer interface {
	mustEmbedUnimplementedWartechServer()
}

func RegisterWartechServer(s grpc.ServiceRegistrar, srv WartechServer) {
	s.RegisterService(&Wartech_ServiceDesc, srv)
}

func _Wartech_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WartechServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wartech.Wartech/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WartechServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wartech_Authentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WartechServer).Authentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wartech.Wartech/Authentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WartechServer).Authentication(ctx, req.(*AuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wartech_CheckUserOrEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserOrEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WartechServer).CheckUserOrEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wartech.Wartech/CheckUserOrEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WartechServer).CheckUserOrEmail(ctx, req.(*CheckUserOrEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wartech_ForgottenPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgottenPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WartechServer).ForgottenPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wartech.Wartech/ForgottenPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WartechServer).ForgottenPassword(ctx, req.(*ForgottenPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wartech_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WartechServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wartech.Wartech/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WartechServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wartech_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WartechServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wartech.Wartech/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WartechServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wartech_ConfirmEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WartechServer).ConfirmEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wartech.Wartech/ConfirmEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WartechServer).ConfirmEmail(ctx, req.(*ConfirmEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Wartech_ServiceDesc is the grpc.ServiceDesc for Wartech service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wartech_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wartech.Wartech",
	HandlerType: (*WartechServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Wartech_Register_Handler,
		},
		{
			MethodName: "Authentication",
			Handler:    _Wartech_Authentication_Handler,
		},
		{
			MethodName: "CheckUserOrEmail",
			Handler:    _Wartech_CheckUserOrEmail_Handler,
		},
		{
			MethodName: "ForgottenPassword",
			Handler:    _Wartech_ForgottenPassword_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Wartech_ChangePassword_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Wartech_GetUser_Handler,
		},
		{
			MethodName: "ConfirmEmail",
			Handler:    _Wartech_ConfirmEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wartech.proto",
}
